### ISSUE TITLE
why it show duplicate  messages when I reSubscribe the topic?

### ISSUE THREAD

**Issue by SuYungCheng** [anoop4real/Flutter_mqtt_new#1]
The first time I subscribe a Topic, and  publish a message. It will shows "EXAMPLE::Change notification:: topic is..." one time.

When I UnSubscribe and Subscribe again, and publish a message. It will show "EXAMPLE::Change notification:: topic is..." twice.

I don't know why?
please do me a favor.
Thanks!

**Comment by anoop4real** [comment]
Hi @SuYungCheng 
Are you getting this issue in the example app or in your own implementation?

**Comment by anoop4real** [comment]
@SuYungCheng Found the issue and fixed it, take an update on the master branch and thanks a lot for raising this. Please let me know you are able to see the issue fixed.

**Comment by SuYungCheng** [comment]
I appreciate it.
It works fine.
You're a life saver.

I can't wait for your new magnum opus.
